language: node_js

node:
  - '12'

before_script:
  - npm install -g mocha
  - npm install --dev

cache:
  npm: false

script:
  - mocha tests/function.test.js
  - mocha tests/output.test.js

branches:
  except:
  - dev

  
jobs:
  include:
    - os: linux
      dist: bionic
    - os: osx
      osx_image: xcode11.4
    - os: windows