language: node_js

node:
  - '12'

before_script:
  - npm install -g jest
  - npm install --dev

cache:
  npm: false

script:
  - jest --runInBand

branches:
  except:
  - dev

  
jobs:
  include:
    - os: linux
      dist: bionic
    - os: osx
      osx_image: xcode11.4